// ISO Timestamp: 2025-11-24T18:10:00Z
/**
 * check_invoice.js – AIVS CIS/VAT Compliance Route
 * Pipeline:
 *   Dropzone → Docling → Compliance Engine → HTML Preview
 *   → PDF/DOCX → Automatic Email (if provided)
 */

import express from "express";
import multer from "multer";
import fs from "fs";
import path from "path";

import { extractInvoice } from "../../docling_extract.js";
import { runComplianceChecks } from "../../compliance_engine.js";
import { sendReportEmail } from "../../server.js";

import { PDFDocument, StandardFonts } from "pdf-lib";
import {
  Document,
  Packer,
  Paragraph,
  TextRun
} from "docx";

const router = express.Router();

/* -----------------------------------------------------------
   DIRECTORIES
----------------------------------------------------------- */
const uploadDir = "/opt/render/project/src/uploads";
const generatedDir = "/opt/render/project/src/generated";

if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });
if (!fs.existsSync(generatedDir)) fs.mkdirSync(generatedDir, { recursive: true });

/* -----------------------------------------------------------
   MULTER UPLOAD HANDLER
----------------------------------------------------------- */
const upload = multer({
  dest: uploadDir,
  limits: { fileSize: 25 * 1024 * 1024 } // 25MB
});

/* -----------------------------------------------------------
   STANDARD FOOTER (PDF & DOCX ONLY)
----------------------------------------------------------- */
const FOOTER_TEXT = `
© AIVS Software Limited 2025 · All rights reserved.
Generated by the AIVS CIS/VAT Compliance Checker for internal advisory use.
This report does not constitute accounting or legal advice.
Prepared for internal management review only · Not for external distribution.
`;

/* -----------------------------------------------------------
   PDF GENERATOR (Professional Layout)
----------------------------------------------------------- */
async function generatePDF(aiReply, timestamp) {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]); // A4 portrait
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  let y = 800;
  const lineHeight = 18;

  const write = (text, size = 12) => {
    page.drawText(text, { x: 40, y, size, font });
    y -= lineHeight;
  };

  // Title
  write("AIVS CIS/VAT Compliance Report", 18);
  y -= 6;
  write(`Generated: ${timestamp}`);
  y -= 20;

  // VAT Section
  write("VAT Assessment", 14);
  write(`VAT Check: ${aiReply.vat_check}`);
  write("");
  y -= 10;

  // CIS Section
  write("CIS Assessment", 14);
  write(`CIS Check: ${aiReply.cis_check}`);
  write("");
  y -= 10;

  // Wording
  write("Required Invoice Wording", 14);
  write(aiReply.required_wording || "None detected");
  write("");
  y -= 10;

  // Summary
  write("Summary Overview", 14);
  aiReply.summary.split("\n").forEach((line) => write(line.trim()));
  write("");
  y -= 20;

  // Footer
  FOOTER_TEXT.split("\n").forEach((line) => write(line.trim()));

  return await pdfDoc.save();
}

/* -----------------------------------------------------------
   DOCX GENERATOR (Professional Layout)
----------------------------------------------------------- */
async function generateDOCX(aiReply, timestamp) {
  const children = [
    new Paragraph({
      children: [
        new TextRun({ text: "AIVS CIS/VAT Compliance Report", bold: true, size: 32 })
      ],
      spacing: { after: 200 }
    }),

    new Paragraph({
      children: [new TextRun({ text: `Generated: ${timestamp}`, size: 22 })],
      spacing: { after: 300 }
    }),

    new Paragraph({
      children: [new TextRun({ text: "VAT Assessment", bold: true, size: 26 })],
      spacing: { after: 200 }
    }),
    new Paragraph({ text: `VAT Check: ${aiReply.vat_check}`, spacing: { after: 200 } }),

    new Paragraph({
      children: [new TextRun({ text: "CIS Assessment", bold: true, size: 26 })],
      spacing: { after: 200 }
    }),
    new Paragraph({ text: `CIS Check: ${aiReply.cis_check}`, spacing: { after: 200 } }),

    new Paragraph({
      children: [new TextRun({ text: "Required Invoice Wording", bold: true, size: 26 })],
      spacing: { after: 200 }
    }),
    new Paragraph({ text: aiReply.required_wording || "None detected", spacing: { after: 300 } }),

    new Paragraph({
      children: [new TextRun({ text: "Summary Overview", bold: true, size: 26 })],
      spacing: { after: 200 }
    }),
    ...aiReply.summary.split("\n").map(
      (line) => new Paragraph({ text: line.trim(), spacing: { after: 100 } })
    ),

    new Paragraph({
      children: [
        new TextRun({
          text: FOOTER_TEXT,
          size: 20
        })
      ],
      spacing: { before: 400 }
    })
  ];

  const doc = new Document({ sections: [{ children }] });
  return await Packer.toBuffer(doc);
}

/* -----------------------------------------------------------
   MAIN ROUTE: /check_invoice
----------------------------------------------------------- */
router.post("/check_invoice", upload.single("file"), async (req, res) => {
  const timestamp = new Date().toISOString();

  try {
    if (!req.file) {
      return res.json({
        success: false,
        html: `<div style="color:#c0392b;">❌ No invoice file uploaded.</div>`
      });
    }

    /* ----------------------------------------------------------
       Read frontend fields (safe defaults if missing)
    ---------------------------------------------------------- */
    const {
      vatCategory = "",
      endUserConfirmed = "",
      cisRate = "",
      partyRole = "",
      userEmail = "",
      emailCopy1 = "",
      emailCopy2 = ""
    } = req.body;

    /* ----------------------------------------------------------
       1. Docling Extraction
    ---------------------------------------------------------- */
    const docResult = await extractInvoice(req.file.path);

    if (docResult.status !== "ok") {
      return res.json({
        success: false,
        html: `<div style="color:#c0392b;font-weight:600;">
                 ❌ Unable to read PDF<br>
                 ${docResult.error || docResult.message}
               </div>`
      });
    }

    /* ----------------------------------------------------------
       2. Compliance Engine
    ---------------------------------------------------------- */
    const aiReply = runComplianceChecks(docResult.extracted);

    /* ----------------------------------------------------------
       3. HTML PREVIEW (Shown on screen ONLY)
    ---------------------------------------------------------- */
    const html = `
      <div style="padding:12px;">
        <h3 style="color:#4e65ac;font-size:18px;font-weight:700;">
          AIVS CIS/VAT Compliance Report
        </h3>

        <p><strong>VAT Check:</strong><br>${aiReply.vat_check}</p>
        <p><strong>CIS Check:</strong><br>${aiReply.cis_check}</p>
        <p><strong>Required Wording:</strong><br>${aiReply.required_wording}</p>

        <p><strong>Summary:</strong><br>${
          aiReply.summary.replace(/\n/g, "<br>")
        }</p>

        <h4 style="color:#4e65ac;margin-top:20px;">
          Draft Corrected Invoice (Screen Only)
        </h4>
        <div style="border:1px solid #ddd;padding:10px;background:#fafafa;">
          ${aiReply.corrected_invoice}
        </div>

        <div style="margin-top:20px;color:#999;font-size:12px;">
          Generated: ${timestamp}
        </div>
      </div>
    `;

    /* ----------------------------------------------------------
       4. Generate PDF + DOCX (no invoice preview included)
    ---------------------------------------------------------- */
    const docBuffer = await generateDOCX(aiReply, timestamp);
    const pdfBuffer = await generatePDF(aiReply, timestamp);

    const safeTime = timestamp.replace(/[:]/g, "-");
    const docPath = path.join(generatedDir, `report_${safeTime}.docx`);
    const pdfPath = path.join(generatedDir, `report_${safeTime}.pdf`);

    fs.writeFileSync(docPath, docBuffer);
    fs.writeFileSync(pdfPath, pdfBuffer);

    /* ----------------------------------------------------------
       5. Automatic email dispatch
    ---------------------------------------------------------- */
    if (userEmail || emailCopy1 || emailCopy2) {
      await sendReportEmail(
        userEmail,
        [emailCopy1, emailCopy2],
        docPath,
        pdfPath,
        timestamp
      );
    }

    /* ----------------------------------------------------------
       6. Return HTML to Frontend
    ---------------------------------------------------------- */
    return res.json({ success: true, html, timestamp });

  } catch (err) {
    console.error("❌ check_invoice.js ERROR:", err);
    return res.json({
      success: false,
      html: `<div style="color:#c0392b;">
              ❌ Server error:<br>${err.message}
            </div>`
    });
  }
});

export default router;
